# This workflow will install Python dependencies, run tests and lint with a single version of Python
name: Build
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEVELOPER: ${{ secrets.DEVELOPER }}
      ARC_SITE: ${{ secrets.ARC_SITE }}
      ARC_NAME: ${{ secrets.ARC_NAME }}
      ARC_PASSWORD: ${{ secrets.ARC_PASSWORD }}
      SH_ID: ${{ secrets.SH_ID }}
      SH_SECRET: ${{ secrets.SH_SECRET }}
      OD_ID: ${{ secrets.OD_ID }}
      OD_SECRET: ${{ secrets.OD_SECRET }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --config="./setup.cfg"
    - name: Test with pytest
      run: |
        pytest . -vs
